In [1]:
# Import Dependencies
import pandas as pd

In [2]:
# A seriously gigantic DataFrame of individuals' names, their trainers, their weight, and their days as gym members
training_data = pd.DataFrame({
    "Name":["Gino Walker","Hiedi Wasser","Kerrie Wetzel","Elizabeth Sackett","Jack Mitten","Madalene Wayman","Jamee Horvath","Arlena Reddin","Tula Levan","Teisha Dreier","Leslie Carrier","Arlette Hartson","Romana Merkle","Heath Viviani","Andres Zimmer","Allyson Osman","Yadira Caggiano","Jeanmarie Friedrichs","Leann Ussery","Bee Mom","Pandora Charland","Karena Wooten","Elizabet Albanese","Augusta Borjas","Erma Yadon","Belia Lenser","Karmen Sancho","Edison Mannion","Sonja Hornsby","Morgan Frei","Florencio Murphy","Christoper Hertel","Thalia Stepney","Tarah Argento","Nicol Canfield","Pok Moretti","Barbera Stallings","Muoi Kelso","Cicely Ritz","Sid Demelo","Eura Langan","Vanita An","Frieda Fuhr","Ernest Fitzhenry","Ashlyn Tash","Melodi Mclendon","Rochell Leblanc","Jacqui Reasons","Freeda Mccroy","Vanna Runk","Florinda Milot","Cierra Lecompte","Nancey Kysar","Latasha Dalton","Charlyn Rinaldi","Erline Averett","Mariko Hillary","Rosalyn Trigg","Sherwood Brauer","Hortencia Olesen","Delana Kohut","Geoffrey Mcdade","Iona Delancey","Donnie Read","Cesar Bhatia","Evia Slate","Kaye Hugo","Denise Vento","Lang Kittle","Sherry Whittenberg","Jodi Bracero","Tamera Linneman","Katheryn Koelling","Tonia Shorty","Misha Baxley","Lisbeth Goering","Merle Ladwig","Tammie Omar","Jesusa Avilla","Alda Zabala","Junita Dogan","Jessia Anglin","Peggie Scranton","Dania Clodfelter","Janis Mccarthy","Edmund Galusha","Tonisha Posey","Arvilla Medley","Briana Barbour","Delfina Kiger","Nia Lenig","Ricarda Bulow","Odell Carson","Nydia Clonts","Andree Resendez","Daniela Puma","Sherill Paavola","Gilbert Bloomquist","Shanon Mach","Justin Bangert","Arden Hokanson","Evelyne Bridge","Hee Simek","Ward Deangelis","Jodie Childs","Janis Boehme","Beaulah Glowacki","Denver Stoneham","Tarra Vinton","Deborah Hummell","Ulysses Neil","Kathryn Marques","Rosanna Dake","Gavin Wheat","Tameka Stoke","Janella Clear","Kaye Ciriaco","Suk Bloxham","Gracia Whaley","Philomena Hemingway","Claudette Vaillancourt","Olevia Piche","Trey Chiles","Idalia Scardina","Jenine Tremble","Herbert Krider","Alycia Schrock","Miss Weibel","Pearlene Neidert","Kina Callender","Charlotte Skelley","Theodora Harrigan","Sydney Shreffler","Annamae Trinidad","Tobi Mumme","Rosia Elliot","Debbra Putt","Rena Delosantos","Genna Grennan","Nieves Huf","Berry Lugo","Ayana Verdugo","Joaquin Mazzei","Doris Harmon","Patience Poss","Magaret Zabel","Marylynn Hinojos","Earlene Marcantel","Yuki Evensen","Rema Gay","Delana Haak","Patricia Fetters","Vinnie Elrod","Octavia Bellew","Burma Revard","Lakenya Kato","Vinita Buchner","Sierra Margulies","Shae Funderburg","Jenae Groleau","Louetta Howie","Astrid Duffer","Caron Altizer","Kymberly Amavisca","Mohammad Diedrich","Thora Wrinkle","Bethel Wiemann","Patria Millet","Eldridge Burbach","Alyson Eddie","Zula Hanna","Devin Goodwin","Felipa Kirkwood","Kurtis Kempf","Kasey Lenart","Deena Blankenship","Kandra Wargo","Sherrie Cieslak","Ron Atha","Reggie Barreiro","Daria Saulter","Tandra Eastman","Donnell Lucious","Talisha Rosner","Emiko Bergh","Terresa Launius","Margy Hoobler","Marylou Stelling","Lavonne Justice","Kala Langstaff","China Truett","Louanne Dussault","Thomasena Samaniego","Charlesetta Tarbell","Fatimah Lade","Malisa Cantero","Florencia Litten","Francina Fraise","Patsy London","Deloris Mclaughlin"],
    "Trainer":['Bettyann Savory','Mariah Barberio','Gordon Perrine','Pa Dargan','Blanch Victoria','Aldo Byler','Aldo Byler','Williams Camire','Junie Ritenour','Gordon Perrine','Bettyann Savory','Mariah Barberio','Aldo Byler','Barton Stecklein','Bettyann Savory','Barton Stecklein','Gordon Perrine','Pa Dargan','Aldo Byler','Brittani Brin','Bettyann Savory','Phyliss Houk','Bettyann Savory','Junie Ritenour','Aldo Byler','Calvin North','Brittani Brin','Junie Ritenour','Blanch Victoria','Brittani Brin','Bettyann Savory','Blanch Victoria','Mariah Barberio','Bettyann Savory','Blanch Victoria','Brittani Brin','Junie Ritenour','Pa Dargan','Gordon Perrine','Phyliss Houk','Pa Dargan','Mariah Barberio','Phyliss Houk','Phyliss Houk','Calvin North','Williams Camire','Brittani Brin','Gordon Perrine','Bettyann Savory','Bettyann Savory','Pa Dargan','Phyliss Houk','Barton Stecklein','Blanch Victoria','Coleman Dunmire','Phyliss Houk','Blanch Victoria','Pa Dargan','Harland Coolidge','Calvin North','Bettyann Savory','Phyliss Houk','Bettyann Savory','Harland Coolidge','Gordon Perrine','Junie Ritenour','Harland Coolidge','Blanch Victoria','Mariah Barberio','Coleman Dunmire','Aldo Byler','Bettyann Savory','Gordon Perrine','Bettyann Savory','Barton Stecklein','Harland Coolidge','Aldo Byler','Aldo Byler','Pa Dargan','Junie Ritenour','Brittani Brin','Junie Ritenour','Gordon Perrine','Mariah Barberio','Mariah Barberio','Mariah Barberio','Bettyann Savory','Brittani Brin','Aldo Byler','Phyliss Houk','Blanch Victoria','Pa Dargan','Phyliss Houk','Brittani Brin','Barton Stecklein','Coleman Dunmire','Bettyann Savory','Bettyann Savory','Gordon Perrine','Blanch Victoria','Junie Ritenour','Phyliss Houk','Coleman Dunmire','Williams Camire','Harland Coolidge','Williams Camire','Aldo Byler','Harland Coolidge','Gordon Perrine','Brittani Brin','Coleman Dunmire','Calvin North','Phyliss Houk','Brittani Brin','Aldo Byler','Bettyann Savory','Brittani Brin','Gordon Perrine','Calvin North','Harland Coolidge','Coleman Dunmire','Harland Coolidge','Aldo Byler','Junie Ritenour','Blanch Victoria','Harland Coolidge','Blanch Victoria','Junie Ritenour','Harland Coolidge','Junie Ritenour','Gordon Perrine','Brittani Brin','Coleman Dunmire','Williams Camire','Junie Ritenour','Brittani Brin','Calvin North','Barton Stecklein','Barton Stecklein','Mariah Barberio','Coleman Dunmire','Bettyann Savory','Mariah Barberio','Pa Dargan','Barton Stecklein','Coleman Dunmire','Brittani Brin','Barton Stecklein','Pa Dargan','Barton Stecklein','Junie Ritenour','Bettyann Savory','Williams Camire','Pa Dargan','Calvin North','Williams Camire','Coleman Dunmire','Aldo Byler','Barton Stecklein','Coleman Dunmire','Blanch Victoria','Mariah Barberio','Mariah Barberio','Harland Coolidge','Barton Stecklein','Phyliss Houk','Pa Dargan','Bettyann Savory','Barton Stecklein','Harland Coolidge','Junie Ritenour','Pa Dargan','Mariah Barberio','Blanch Victoria','Williams Camire','Phyliss Houk','Phyliss Houk','Coleman Dunmire','Mariah Barberio','Gordon Perrine','Coleman Dunmire','Brittani Brin','Pa Dargan','Coleman Dunmire','Brittani Brin','Blanch Victoria','Coleman Dunmire','Gordon Perrine','Coleman Dunmire','Aldo Byler','Aldo Byler','Mariah Barberio','Williams Camire','Phyliss Houk','Aldo Byler','Williams Camire','Aldo Byler','Williams Camire','Coleman Dunmire','Phyliss Houk'],
    "Weight":[128,180,193,177,237,166,224,208,177,241,114,161,162,151,220,142,193,193,124,130,132,141,190,239,213,131,172,127,184,157,215,122,181,240,218,205,239,217,234,158,180,131,194,171,177,110,117,114,217,123,248,189,198,127,182,121,224,111,151,170,188,150,137,231,222,186,139,175,178,246,150,154,129,216,144,198,228,183,173,129,157,199,186,232,172,157,246,239,214,161,132,208,187,224,164,177,175,224,219,235,112,241,243,179,208,196,131,207,182,233,191,162,173,197,190,182,231,196,196,143,250,174,138,135,164,204,235,192,114,179,215,127,185,213,250,213,153,217,176,190,119,167,118,208,113,206,200,236,159,218,168,159,156,183,121,203,215,209,179,219,174,220,129,188,217,250,166,157,112,236,182,144,189,243,238,147,165,115,160,134,245,174,238,157,150,184,174,134,134,248,199,165,117,119,162,112,170,224,247,217],
    "Membership (Days)":[52,70,148,124,186,157,127,155,37,185,158,129,93,69,124,13,76,153,164,161,48,121,167,69,39,163,7,34,176,169,108,162,195,86,155,77,197,200,80,142,179,67,58,145,188,147,125,15,13,173,125,4,61,29,132,110,62,137,197,135,162,174,32,151,149,65,18,42,63,62,104,200,189,40,38,199,1,12,8,2,195,30,7,72,130,144,2,34,200,143,43,196,22,115,171,54,143,59,14,52,109,115,187,185,26,19,178,18,120,169,45,52,130,69,168,178,96,22,78,152,39,51,118,130,60,156,108,69,103,158,165,142,86,91,117,77,57,169,86,188,97,111,22,83,81,177,163,35,12,164,21,181,171,138,22,107,58,51,38,128,19,193,157,13,104,89,13,10,26,190,179,101,7,159,100,49,120,109,56,199,51,108,47,171,69,162,74,119,148,88,32,159,65,146,140,171,88,18,59,13]
})
training_data.head()

                Name          Trainer  Weight  Membership (Days)
0        Gino Walker  Bettyann Savory     128                 52
1       Hiedi Wasser  Mariah Barberio     180                 70
2      Kerrie Wetzel   Gordon Perrine     193                148
3  Elizabeth Sackett        Pa Dargan     177                124
4        Jack Mitten  Blanch Victoria     237                186

In [3]:
# Convert the membership days into weeks and then add a this data in a new column to the DataFrame.
weeks = training_data["Membership (Days)"]/7
training_data["Membership (Weeks)"] = weeks

training_data.head()

,Name,Trainer,Weight,Membership (Days),Membership (Weeks)
0,Gino Walker,Bettyann Savory,128,52,7.428571
1,Hiedi Wasser,Mariah Barberio,180,70,10.000000
2,Kerrie Wetzel,Gordon Perrine,193,148,21.142857
3,Elizabeth Sackett,Pa Dargan,177,124,17.714286
4,Jack Mitten,Blanch Victoria,237,186,26.571429

In [4]:
# Create a Dataframe that has the Trainer, Weight, and Membership.
trainers_data =  training_data[["Trainer", "Weight", "Membership (Days)", "Membership (Weeks)"]]
trainers_data

              Trainer  Weight  Membership (Days)  Membership (Weeks)
0     Bettyann Savory     128                 52            7.428571
1     Mariah Barberio     180                 70           10.000000
2      Gordon Perrine     193                148           21.142857
3           Pa Dargan     177                124           17.714286
4     Blanch Victoria     237                186           26.571429
5          Aldo Byler     166                157           22.428571
6          Aldo Byler     224                127           18.142857
7     Williams Camire     208                155           22.142857
8      Junie Ritenour     177                 37            5.285714
9      Gordon Perrine     241                185           26.428571
10    Bettyann Savory     114                158           22.571429
11    Mariah Barberio     161                129           18.428571
12         Aldo Byler     162                 93           13.285714
13   Barton Stecklein     151                 69            9.857143
14    Bettyann Savory     220                124           17.714286
15   Barton Stecklein     142                 13            1.857143
16     Gordon Perrine     193                 76           10.857143
17          Pa Dargan     193                153           21.857143
18         Aldo Byler     124                164           23.428571
19      Brittani Brin     130                161           23.000000
20    Bettyann Savory     132                 48            6.857143
21       Phyliss Houk     141                121           17.285714
22    Bettyann Savory     190                167           23.857143
23     Junie Ritenour     239                 69            9.857143
24         Aldo Byler     213                 39            5.571429
25       Calvin North     131                163           23.285714
26      Brittani Brin     172                  7            1.000000
27     Junie Ritenour     127                 34            4.857143
28    Blanch Victoria     184                176           25.142857
29      Brittani Brin     157                169           24.142857
..                ...     ...                ...                 ...
170    Junie Ritenour     182                179           25.571429
171         Pa Dargan     144                101           14.428571
172   Mariah Barberio     189                  7            1.000000
173   Blanch Victoria     243                159           22.714286
174   Williams Camire     238                100           14.285714
175      Phyliss Houk     147                 49            7.000000
176      Phyliss Houk     165                120           17.142857
177   Coleman Dunmire     115                109           15.571429
178   Mariah Barberio     160                 56            8.000000
179    Gordon Perrine     134                199           28.428571
180   Coleman Dunmire     245                 51            7.285714
181     Brittani Brin     174                108           15.428571
182         Pa Dargan     238                 47            6.714286
183   Coleman Dunmire     157                171           24.428571
184     Brittani Brin     150                 69            9.857143
185   Blanch Victoria     184                162           23.142857
186   Coleman Dunmire     174                 74           10.571429
187    Gordon Perrine     134                119           17.000000
188   Coleman Dunmire     134                148           21.142857
189        Aldo Byler     248                 88           12.571429
190        Aldo Byler     199                 32            4.571429
191   Mariah Barberio     165                159           22.714286
192   Williams Camire     117                 65            9.285714
193      Phyliss Houk     119                146           20.857143
194        Aldo Byler     162                140           20.000000
195   Williams Camire     112                171           24.428571
196        Aldo Byler     170                 88           12.571429
197   Williams Camire     224                 18            2.571429
198   Coleman Dunmire     247                 59            8.428571
199      Phyliss Houk     217                 13            1.857143

[200 rows x 4 columns]

In [5]:
# Using groupby get the average weight and length membership for each trainer.

trainers_means = trainers_data.groupby(["Trainer"]).mean()
trainers_means

                      Weight  Membership (Days)  Membership (Weeks)
Trainer
Aldo Byler        183.000000         103.529412           14.789916
Barton Stecklein  174.384615          81.153846           11.593407
Bettyann Savory   179.200000         102.350000           14.621429
Blanch Victoria   189.571429         101.071429           14.438776
Brittani Brin     182.875000         111.000000           15.857143
Calvin North      158.571429          99.285714           14.183673
Coleman Dunmire   194.411765          98.647059           14.092437
Gordon Perrine    185.142857         106.285714           15.183673
Harland Coolidge  182.750000         106.166667           15.166667
Junie Ritenour    179.571429          86.928571           12.418367
Mariah Barberio   170.866667         110.133333           15.733333
Pa Dargan         186.071429         108.285714           15.469388
Phyliss Houk      174.000000          98.812500           14.116071
Williams Camire   177.818182         111.727273           15.961039

In [ ]:
trainers_means.sort_values(by='Membership (Days)', ascending=False)